language: node_js
cache:
    directories:
        - ~/.npm
notifications:
    email: false
dist: focal
arch:
    - amd64
    - arm64
node_js:
    - 12
    - lts/*
    - node
os: linux
script:
    - npm run test && npm run build

jobs:
    include:
        - stage: coverage
          name: Coverage
          node_js: 14
          script: npm run test; npm run report-coverage
